### PR TITLE
fix Assistant Builder form Select values (#201)

### LINKED ISSUE #201: BUG: AssistantBuilder - SelectArchitecture
### Overview
On assistant edit, "Select architecture" doesn't seem to grab the selected architecture.

### Reproduce
1. Select an assistant from the AssistantSelector.
2. Notice that "Select architecture" does not reflect the assistant's architecture.

Screenshot 2024-09-21 at 8 59 49 PM

### PR DESCRIPTION
**Pull request by s2sa4v**
Fixes Selectors in the Assistant Builder.
It should load proper values for Architecture, Agent Type, and LLM Type.

Closes #201

### CODE REVIEW

File: ui/src/components/features/build-panel/components/form-select.tsx [hunk 1]
```diff
@@ -32,7 +38,7 @@ export function FormSelect({ form, title ,options, formName, placeholder }: TFor
         <FormItem className="flex flex-col">
           <FormLabel>{title}</FormLabel>
           <FormControl>
-            <Select onValueChange={field.onChange} defaultValue={field.value}>
+            <Select onValueChange={field.onChange} value={field.value}>
```
Comment (krishokr) [inline ui/src/components/features/build-panel/components/form-select.tsx:41]: Oh. That was the problem. I feel like I glazed right over this and tried a ton of other things... lol. Thank you Stas!

File: ui/src/components/features/build-panel/components/edit-assistant.tsx [hunk 2]
```diff
@@ -20,13 +20,30 @@ const RetrievalType = "retrieval";
...
 export function EditAssistant() {
   const { assistantId } = useSlugRoutes();
-
   const { data: selectedAssistant, isLoading: isLoadingAssistant } =
     useAssistant(assistantId as string, {
       enabled: !!assistantId,
     });
 
-  const updateAssistant = useUpdateAssistant(selectedAssistant?.id as string);
+  return isLoadingAssistant ? (
```
Comment (krishokr) [inline ui/src/components/features/build-panel/components/edit-assistant.tsx:28]: I am guessing this has something to do with the behavior I was seeing in System prompt... but yeah, I am utterly confused.

**Review by krishokr — APPROVED** [review]
Thanks a ton!!
